//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfaceApplicationMaurice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurfaceApplicationMaurice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your selection.
        /// </summary>
        internal static string AccessSelection {
            get {
                return ResourceManager.GetString("AccessSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to your selection.
        /// </summary>
        internal static string Addtoyourselection {
            get {
                return ResourceManager.GetString("Addtoyourselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your picture on book.
        /// </summary>
        internal static string AllPhotoOnBook {
            get {
                return ResourceManager.GetString("AllPhotoOnBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All photo on CD.
        /// </summary>
        internal static string AllPhotoOnCD {
            get {
                return ResourceManager.GetString("AllPhotoOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retournez à la gallerie.
        /// </summary>
        internal static string backToGallery {
            get {
                return ResourceManager.GetString("backToGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bags.
        /// </summary>
        internal static string Bags {
            get {
                return ResourceManager.GetString("Bags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and white.
        /// </summary>
        internal static string Blackandwhite {
            get {
                return ResourceManager.GetString("Blackandwhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber number.
        /// </summary>
        internal static string Chambernumber {
            get {
                return ResourceManager.GetString("Chambernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a category.
        /// </summary>
        internal static string ChoiceACategory {
            get {
                return ResourceManager.GetString("ChoiceACategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice by Category.
        /// </summary>
        internal static string ChoicebyCategory {
            get {
                return ResourceManager.GetString("ChoicebyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice by Date.
        /// </summary>
        internal static string ChoicebyDate {
            get {
                return ResourceManager.GetString("ChoicebyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Format for photo and Order your CD.
        /// </summary>
        internal static string ChooseFormatAndCD {
            get {
                return ResourceManager.GetString("ChooseFormatAndCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Effect.
        /// </summary>
        internal static string Chooseyoureffect {
            get {
                return ResourceManager.GetString("Chooseyoureffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Information.
        /// </summary>
        internal static string CloseInformation {
            get {
                return ResourceManager.GetString("CloseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string Createaccount {
            get {
                return ResourceManager.GetString("Createaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your login/password.
        /// </summary>
        internal static string CreateyourLogin {
            get {
                return ResourceManager.GetString("CreateyourLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Image.
        /// </summary>
        internal static string Deleteimage {
            get {
                return ResourceManager.GetString("Deleteimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove source picture?.
        /// </summary>
        internal static string DeleteImageSource {
            get {
                return ResourceManager.GetString("DeleteImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date.
        /// </summary>
        internal static string Departuredate {
            get {
                return ResourceManager.GetString("Departuredate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want use this effect ?.
        /// </summary>
        internal static string Doyourealywant {
            get {
                return ResourceManager.GetString("Doyourealywant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating login.
        /// </summary>
        internal static string Errorcreatelogin {
            get {
                return ResourceManager.GetString("Errorcreatelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error login.
        /// </summary>
        internal static string Errorlogin {
            get {
                return ResourceManager.GetString("Errorlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15x23.
        /// </summary>
        internal static string F_1523 {
            get {
                return ResourceManager.GetString("F_1523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20x30.
        /// </summary>
        internal static string F_2030 {
            get {
                return ResourceManager.GetString("F_2030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30x45.
        /// </summary>
        internal static string F_3045 {
            get {
                return ResourceManager.GetString("F_3045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40x60.
        /// </summary>
        internal static string F_4060 {
            get {
                return ResourceManager.GetString("F_4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50x75.
        /// </summary>
        internal static string F_5075 {
            get {
                return ResourceManager.GetString("F_5075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60x95.
        /// </summary>
        internal static string F_6095 {
            get {
                return ResourceManager.GetString("F_6095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill entries.
        /// </summary>
        internal static string FillEntry {
            get {
                return ResourceManager.GetString("FillEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstname.
        /// </summary>
        internal static string FirstNameUser {
            get {
                return ResourceManager.GetString("FirstNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                              Format                                          .
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos à imprimer.
        /// </summary>
        internal static string FormatPhotoToPrint {
            get {
                return ResourceManager.GetString("FormatPhotoToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to.
        /// </summary>
        internal static string Gobackto {
            get {
                return ResourceManager.GetString("Gobackto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many pages do you want ?.
        /// </summary>
        internal static string HowManyPages {
            get {
                return ResourceManager.GetString("HowManyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image added to your selection.
        /// </summary>
        internal static string Imageaddedtoyourselection {
            get {
                return ResourceManager.GetString("Imageaddedtoyourselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information english.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Keyenter {
            get {
                return ResourceManager.GetString("Keyenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        internal static string Keyerase {
            get {
                return ResourceManager.GetString("Keyerase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading finish.
        /// </summary>
        internal static string Loadingfinish {
            get {
                return ResourceManager.GetString("Loadingfinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have 20 pages .
        /// </summary>
        internal static string MinimumPhotoOnBook {
            get {
                return ResourceManager.GetString("MinimumPhotoOnBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have 10 pictures minimum.
        /// </summary>
        internal static string MinimumPhotoOnCD {
            get {
                return ResourceManager.GetString("MinimumPhotoOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Montant {
            get {
                return ResourceManager.GetString("Montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mug.
        /// </summary>
        internal static string Mug {
            get {
                return ResourceManager.GetString("Mug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string NameUser {
            get {
                return ResourceManager.GetString("NameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CD photo.
        /// </summary>
        internal static string NoPhotoOnCD {
            get {
                return ResourceManager.GetString("NoPhotoOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of picture.
        /// </summary>
        internal static string NumberImage {
            get {
                return ResourceManager.GetString("NumberImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               Object              .
        /// </summary>
        internal static string Objet {
            get {
                return ResourceManager.GetString("Objet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo on CD whitout printing.
        /// </summary>
        internal static string OnlyOnCD {
            get {
                return ResourceManager.GetString("OnlyOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want a picture book ?.
        /// </summary>
        internal static string OrderBook {
            get {
                return ResourceManager.GetString("OrderBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        Order On CD          .
        /// </summary>
        internal static string OrderOnCD {
            get {
                return ResourceManager.GetString("OrderOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order picutres on CD.
        /// </summary>
        internal static string OrderPictureCD {
            get {
                return ResourceManager.GetString("OrderPictureCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teddy Bear.
        /// </summary>
        internal static string Pelluche {
            get {
                return ResourceManager.GetString("Pelluche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb Page of Book.
        /// </summary>
        internal static string PhotoOnBook {
            get {
                return ResourceManager.GetString("PhotoOnBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos sur le CD.
        /// </summary>
        internal static string PhotoOnCD {
            get {
                return ResourceManager.GetString("PhotoOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos sur produit dérivé.
        /// </summary>
        internal static string PhotoOnOjbet {
            get {
                return ResourceManager.GetString("PhotoOnOjbet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your login/password.
        /// </summary>
        internal static string Pleaseenteryourlogin {
            get {
                return ResourceManager.GetString("Pleaseenteryourlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        internal static string PorteCles {
            get {
                return ResourceManager.GetString("PorteCles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        internal static string Price1 {
            get {
                return ResourceManager.GetString("Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo on print price.
        /// </summary>
        internal static string PricePromotional {
            get {
                return ResourceManager.GetString("PricePromotional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réduction.
        /// </summary>
        internal static string Reduction {
            get {
                return ResourceManager.GetString("Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Selection.
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        internal static string Sepia {
            get {
                return ResourceManager.GetString("Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        internal static string Tapisdesouri {
            get {
                return ResourceManager.GetString("Tapisdesouri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tee Shirt.
        /// </summary>
        internal static string TeeShirt {
            get {
                return ResourceManager.GetString("TeeShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch two times the picture to select it.
        /// </summary>
        internal static string TouchTwoTimeToSelect {
            get {
                return ResourceManager.GetString("TouchTwoTimeToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your command.
        /// </summary>
        internal static string WhatCaddyFor {
            get {
                return ResourceManager.GetString("WhatCaddyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for this photo.
        /// </summary>
        internal static string WhatCaddyFor2 {
            get {
                return ResourceManager.GetString("WhatCaddyFor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
